branches: [master]
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
categories:
  - title: '🚀 Features'
    labels:
      - 'type: feat'
      - 'type: enhancement'
      - 'type: refactor'
      - 'type: test'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type: fix'
      - 'type: bugfix'
      - 'type: bug'
      - 'type: docs'
      - 'type: build'
      - 'type: fix'
  - title: '🧰 Maintenance'
    labels:
      - 'type: chore'
      - 'type: ci'
      - 'type: style'
      - 'type: perf'
