name-template: 'v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  $CONTRIBUTORS
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'improvement'
      - 'refactor'
  - title: '🧩 Continuous Integrations'
    labels:
      - 'ci'
