name-template: 'v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🎨 Refactor'
    labels:
      - 'refactor'
      - 'style'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
  - title: '📝 Docs/Test'
    labels:
      - 'docs'
      - 'test'
