name: Draft new version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release Draft
      uses: release-drafter/release-drafter@v5
      with:
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
