name: Generate a draft Release
on:
  push:
    branches:
      - master
jobs:
  draft-version:
    runs-on: ubuntu-latest
    steps:
    - name: Release Draft
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}