name: Publish to test
on:
  workflow_dispatch:
  push:
    branches:
      - test/centralized-pipeline
jobs:
  push-to-modyo:
    needs: build-widget
    uses: modyo/modyoservices-widgets-github-actions/.github/workflows/build-vue-widget.yml@55ab8f7
    with:
      artifact-name: my-widget
      legacy-peer-deps: false
      build-path: dist/
  # push-to-modyo: 
  #   needs: build-widget 
  #   uses: Giorgiosaud/reused-workflows/.github/workflows/deploy-widget-to-modyo.yml@main
  #   with:
  #     environment: develop # Set env vars in dev env
  #     artifact-name: my-widget
  #   secrets:
  #     modyo-token: ${{ secrets.TOKEN }}
 