name: Publish to test
on:
  push:
    branches:
      - test/centralized-pipeline
jobs:
  call-modyo-workflow:
    uses: Giorgiosaud/reused-workflows/.github/workflows/deploy-widget-to-modyo.yml@main
    secrets:
      modyo-account-url: ${{ secrets.BASE_URL }}
      modyo-token: ${{ secrets.TOKEN }}
      modyo-site-id: ${{ secrets.SITE_ID_CERTIFICATION }}

