name: Publish to test
on:
  push:
    branches:
      - test/centralized-pipeline
jobs:
  call-modyo-workflow:
    uses: modyo/mifel-widgets-accounts-id/.github/workflows/deploy-widget-to-modyo.yml@develop
      with:
        modyo-account-url: ${{secrets.BASE_URL}}
        modyo-token: ${{secrets.TOKEN}}
        modyo-site-id: ${{secrets.SITE_ID_CERTIFICATION}}
